export default {
  REQUEST_BUSINESSES: 'REQUEST_BUSINESSES',
  RECEIVE_BUSINESSES: 'RECEIVE_BUSINESSES',
  DID_CHANGE_CATEGORY: 'DID_CHANGE_CATEGORY',
  DID_CHANGE_CITY: 'DID_CHANGE_CITY',
  DID_LOCK_CATEGORY: 'DID_LOCK_CATEGORY',
};
